#spring.application.name=jwt-oauth2
spring:
  application:
    name: jwt-oauth2

  datasource:
    url: jdbc:postgresql://localhost:5432/authn
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    org.springframework.security: trace